# Generated by Django 3.0.6 on 2020-06-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pensieve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=66, unique=True)),
                ('content', models.TextField()),
                ('upDate', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-upDate'],
            },
        ),
    ]
