# Generated by Django 3.0.6 on 2020-08-10 01:18

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('pensieve', '0002_auto_20200804_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pensieve',
            name='content',
            field=tinymce.models.HTMLField(blank=True),
        ),
    ]
