# Generated by Django 3.0.6 on 2020-06-15 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TheKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner', models.CharField(max_length=60, unique=True)),
                ('shape', models.CharField(max_length=36, unique=True)),
            ],
        ),
    ]
